[package]
name = "icepop-phf"
version = "0.1.0"
edition = "2024"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
portable = { path = "../portable", default-features = false, features = ["default-hasher", "alloc"] }
hashbrown = "0.17"
rkyv = { version = "0.8", default-features = false, features = ["alloc", "bytecheck"], optional = true }
serde = { version = "1", optional = true, default-features = false, features = ["alloc"] }
equivalent = "1.0.2"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_test = "1"

[features]
default = ["getrandom"]
serde = ["dep:serde", "portable/serde"]
rkyv = ["dep:rkyv", "portable/rkyv-0_8"]
getrandom = ["portable/getrandom"]

[lints]
workspace = true
